config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users, only: %i[new create]
  resources :questions do
    resources :answers, except: %i[new show]
  end

  root 'pages#index'
end

app/models/answer.rb
# frozen_string_literal: true

# This shiny device polishes bared Answer
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true, length: { minimum: 5 }

  def formatted_created_at
    created_at.strftime('%Y-%m-%d %H:%M:%S')
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
# frozen_string_literal: true

# This shiny device polishes bared Questions
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  validates :title, presence: true, length: { minimum: 3 }
  validates :body, presence: true, length: { minimum: 3 }
end

app/models/user.rb
# frozen_string_literal: true

# Модель Пользователя
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

# This shiny device polishes bared Answers
class AnswersController < ApplicationController
  include ActionView::RecordIdentifier
  before_action :set_question!
  before_action :set_answer!, except: :create

  def update
    if @answer.update answer_params
      flash[:success] = 'Ответ обновлен!!'
      redirect_to question_path(@question, anchor: dom_id(@answer))
    else
      render :edit
    end
  end

  def edit; end

  def create
    @answer = @question.answers.build answer_params

    if @answer.save
      flash[:success] = 'Ответ создан!'
      redirect_to question_path(@question)
    else
      @answers = @question.answers.order created_at: :desc
      render 'questions/show'
    end
  end

  def destroy
    @answer.destroy
    flash[:success] = 'Ответ удален!'
    redirect_to question_path(@question)
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def set_question!
    @question = Question.find params[:question_id]
  end

  def set_answer!
    @answer = @question.answers.find params[:id]
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Главный контроллер
class ApplicationController < ActionController::Base
  include Pagy::Backend
  include ErrorHandling

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]).decorate if session[:user_id].present?
  end

  def user_signed_in?
    current_user.present?
  end

  helper_method :current_user, :user_signed_in?
end

app/controllers/concerns/authentication.rb
# frozen_string_literal: true

# g
module Authentication
  extend ActiveSupport::Concern

  included do
    private

    def current_user
      @current_user ||= User.find_by(id: session[:user_id]).decorate if session[:user_id].present?
    end

    def user_signed_in?
      current_user.present?
    end

    def require_authentication
      return if user_signed_in?

      flash[:warning] = 'You are not signed in!'
      redirect_to root_path
    end

    def require_no_authentication
      return unless user_signed_in?

      flash[:warning] = 'You are already signed in!'
      redirect_to root_path
    end

    def sign_in(user)
      session[:user_id] = user.id
    end

    def sign_out
      session.delete :user_id
      @current_user = nil
    end

    helper_method :current_user, :user_signed_in?
  end
end

app/controllers/concerns/error_handling.rb
# frozen_string_literal: true

module ErrorHandling
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound, with: :notfound

    private

    def notfound(exception)
      logger.warn exception
      render file: 'public/404.html', status: :not_found, layout: false
    end
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index; end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

# This shiny device polishes bared Questions
class QuestionsController < ApplicationController
  before_action :set_question!, only: %i[show destroy edit update]
  def show
    @question = @question.decorate
    @answer = @question.answers.build
    @pagy, @answers = pagy @question.answers.order(created_at: :desc)
    @answers = @answers.decorate
  end

  def destroy
    @question.destroy
    flash[:success] = 'Вопрос спешно удален!'
    redirect_to questions_path
  end

  def edit; end

  def update
    if @question.update question_params
      flash[:success] = 'Вопрос обновлен успешно!'
      redirect_to questions_path
    else
      render :edit
    end
  end

  def index
    @pagy, @questions = pagy Question.order(created_at: :desc).decorate
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new question_params
    if @question.save
      flash[:success] = 'Вопрос создан!'
      redirect_to questions_path
    else
      render :new
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def set_question!
    @question = Question.find params[:id]
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Контроллер пользавателя
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the app, #{current_user.name_or_email}!"
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Хелпер_главной_страницы
module ApplicationHelper
  include Pagy::Frontend
  def nav_tab(title, url, options = {})
    current_page = options.delete :current_page

    css_class = current_page == title ? 'text-secondary' : 'text-white'

    options[:class] = if options[:class]
                        "#{options[:class]} #{css_class}"
                      else
                        css_class
                      end

    link_to title, url, options
  end

  def currently_at(current_page = '')
    render partial: 'shared/menu', locals: {current_page:}
  end

  def full_title(page_title = '')
    base_title = 'Наш магазин'
    if page_title.present?
      "#{page_title} | #{base_title}"
    else
      base_title
    end
  end
end

app/views/answers/_answer.html.erb
<%= tag.article class: 'mb-3 card', id: dom_id(answer) do %>
  <div class="card-body">
    <section class="card-text">
      <small><time datetime="<%= answer.formatted_created_at %>">
        <%= answer.formatted_created_at %>
      </time></small>

      <div class="mt-2 mb-3">
        <%= sanitize answer.body %>
      </div>
    </section>

    <%= link_to 'Изменить Всё', edit_question_answer_path(question, answer),
                class: 'btn btn-info btn-sm' %>
    <%= link_to 'Удалить', question_answer_path(question, answer), class: 'btn btn-danger btn-sm',
                data: {method: :delete, confirm: "Вы уверены?"} %>
  </div>
<% end %>

app/views/answers/_form.html.erb
<%= render 'shared/errors', object: @answer %>
<%= form_with model: [@question, @answer] do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>

    <div class="col-sm-10">
      <%= f.text_area :body, class: 'form-control' %>
    </div>
  </div>

  <%= f.submit "Отправить ответ!", class: 'btn btn-primary' %>
<% end %>

app/views/answers/edit.html.erb
<% provide :page_title, 'Редактировать ответ' %>
<% currently_at 'Questions' %>

<h1>Редактировать ответ</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="utf-8">
  <title><%= full_title(yield(:page_title)) %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
</head>

<body>
<%= yield :main_menu %>

<main class="container mt-3">
  <% flash.each do |k, v| %>
    <%= tag.div v, class: "alert alert-#{k}", role: 'alert' %>
  <% end %>

  <%= yield %>
</main>
</body>
</html>

app/views/pages/index.html.erb
<% currently_at 'Наш магазин' %>
<% provide :page_title %>

<h1>Наш магазин</h1>

<p>Добро пожаловать</p>

<footer>
  &copy; RS8 <%= Time.now.year %>
</footer>

app/views/questions/_form.html.erb
<%= render 'shared/errors', object: @question %>
<%= form_with model: @question do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :title %>
    </div>

    <div class="col-sm-10">
      <%= f.text_field :title, placeholder: 'Title', class: 'form-control' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>

    <div class="col-sm-10">
      <%= f.text_area :body, class: 'form-control' %>
    </div>
  </div>


  <%= f.submit "Отправить вопрос!", class: 'btn btn-primary' %>
<% end %>

app/views/questions/edit.html.erb
<% provide :page_title, 'Изменить вопрос' %>
<% currently_at 'Questions' %>

<h1 class="mb-4">Изменить вопрос</h1>

<%= render 'form' %>

app/views/questions/index.html.erb
<% provide :page_title, 'Все вопросы' %>
<% currently_at 'Вопросы' %>

<h1 class="mb-4">Все вопросы</h1>

<%= link_to 'Написать новый вопрос', new_question_path, class: 'btn btn-primary btn-lg mb-3' %>

<%== pagy_bootstrap_nav @pagy %>

<% @questions.each do |question| %>
  <article class="card my-3">
    <div class="card-body">
      <h2><%= question.title %></h2>

        <section class="card-text">
          <time datetime="<%= question.formatted_created_at %>">
            <small><%= question.formatted_created_at %></small>
          </time>

          <p class="my-2">
            <%= truncate strip_tags(question.body), length: 150, omission: '... (continued)' %>
          </p>
        </section>

  <%= link_to 'Показать', question_path(question), class: 'btn btn-primary' %> |
  <%= link_to 'Изменить', edit_question_path(question), class: 'btn btn-secondary' %> |
  <%= link_to 'Удалить', question_path(question), class: 'btn btn-danger',
              data: {method: :delete, confirm: 'Вы уверены?'} %>
    </div>
  </article>
<% end %>

<%== pagy_bootstrap_nav @pagy %>

app/views/questions/new.html.erb
<% provide :page_title, 'Новый вопрос' %>
<% currently_at 'Questions' %>

<h1 class="mb-4">Новый вопрос</h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<% provide :page_title, @question.title %>
<% currently_at 'Questions' %>

<h1 class="mb-4"><%= @question.title %></h1>

<time datetime="<%= @question.formatted_created_at %>">
  <%= @question.formatted_created_at %>
</time>

<div class="lead my-3">
  <%= sanitize @question.body %>
</div>

<div class="btn-group">
<%= link_to 'Показать', question_path(@question), class: 'btn btn-primary' %> |
<%= link_to 'Изменить', edit_question_path(@question), class: 'btn btn-secondary' %> |
<%= link_to 'Удалить', question_path(@question), class: 'btn btn-danger',
            data: {method: :delete, confirm: 'Вы уверены?'} %>
</div>

<hr class="my-3">

<h2 class="mb-3">Напишите свой ответ</h2>

<%= render 'answers/form' %>

<h2 class="mt-5">Ответы</h2>

<%== pagy_bootstrap_nav @pagy %>

<%= render partial: 'answers/answer', collection: @answers,
           as: :answer, locals: {question: @question} %>

<%== pagy_bootstrap_nav @pagy %>

app/views/shared/_errors.html.erb
<% if object.errors.full_messages.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_menu.html.erb
<%= provide :main_menu do %>
  <header class="p-3 bg-dark text-white">
    <div class="container">
      <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><%= nav_tab 'Наш магазин', root_path,
                          class: 'nav-link px-2', current_page: current_page %></li>
          <li><%= nav_tab 'Вопросы', questions_path,
                          class: 'nav-link px-2', current_page: current_page %></li>
        </ul>

        <ul class="nav col-12 col-lg-auto mb-2 mb-md-0">
          <% if user_signed_in? %>
            <li>
              <a class="nav-link px-2 text-white" href="#">
                <%= current_user.name_or_email %>
              </a>
            </li>
          <% else %>
            <li><%= nav_tab 'Sign Up', new_user_path,
                            class: 'nav-link px-2', current_page: current_page %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>
 <% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', object: @user %>
<%= form_with model: @user do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :email %>
    </div>

    <div class="col-sm-10">
      <%= f.email_field :email, placeholder: 'Почта', class: 'form-control form-control-lg' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :name %>
    </div>

    <div class="col-sm-10">
      <%= f.text_field :name, placeholder: 'Имя', class: 'form-control form-control-lg' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :password %>
    </div>

    <div class="col-sm-10">
      <%= f.password_field :password, class: 'form-control form-control-lg' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :password_confirmation %>
    </div>

    <div class="col-sm-10">
      <%= f.password_field :password_confirmation, class: 'form-control form-control-lg' %>
    </div>
  </div>

  <%= f.submit "Зарегистрироваться!", class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/users/new.html.erb
<% provide :page_title, 'Регистрация' %>
<% currently_at 'Sign Up' %>

<h1 class="mb-4">Регистрация</h1>

<%= render 'form' %>